# Generated by Django 3.2.5 on 2021-07-10 18:53

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=users.models.plant_directory_path)),
                ('health', models.IntegerField(default=0)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('records', models.ManyToManyField(related_name='record_owner_plant', to='users.Record')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.species')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='plants',
            field=models.ManyToManyField(to='users.Plant'),
        ),
    ]
