# Generated by Django 3.2.5 on 2021-07-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210710_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='records',
            field=models.ManyToManyField(blank=True, related_name='record_owner_plant', to='users.Record'),
        ),
    ]
