# Generated by Django 3.2.5 on 2021-07-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_plant_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='nickname',
            field=models.CharField(default='Pancho The Cactus', max_length=40),
            preserve_default=False,
        ),
    ]
