# Generated by Django 3.2.5 on 2021-07-11 18:38

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_record_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to=users.models.plant_directory_path),
        ),
    ]
